export const FILTER_ACTIONS = {
  FETCHING_NEWS: 'FETCHING_NEWS',
  FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
  FETCH_NEWS_ERROR: 'FETCH_NEWS_ERROR',
  CHANGE_INPUT: 'CHANGE_INPUT',
  CHANGE_PAGE: 'CHANGE_PAGE',
};
